### ISSUE TITLE
[question] can Apigility only be used with PHP?

### ISSUE THREAD

**Issue by weierophinney** [laminas-api-tools/documentation#5]
I have some confusion about Apigility.

Is it a library or a gateway like Kong, tyk etc? If its a gateway then it shouldn't matter how proxied APIs are written perhaps in Python, Java etc.

However, on the website it says "You can use Apigility in any PHP application, using all the libraries and frameworks that you want."

Is it true? 

---

Originally posted by @peacemakr at https://github.com/zfcampus/apigility-documentation/issues/75

**Comment by javabudd** [comment]
doesn't seem like the right place for this question...

**Comment by Ocramius** [comment]
Closing here: not really relevant.
